// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs4SKrb-hglPUZUmCPQsB7RGbIT9FSsxg',
    appId: '1:423502301630:web:89321088ba409d478a11ef',
    messagingSenderId: '423502301630',
    projectId: 'comtwittercloneapp',
    authDomain: 'comtwittercloneapp.firebaseapp.com',
    storageBucket: 'comtwittercloneapp.firebasestorage.app',
    measurementId: 'G-E6VWX78N3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO3dx__0Erdqn9zaJmdJN37H-LegSTVTw',
    appId: '1:423502301630:android:1d1a6d2fa80302f28a11ef',
    messagingSenderId: '423502301630',
    projectId: 'comtwittercloneapp',
    storageBucket: 'comtwittercloneapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUmAaT-wRV0du93tULbs9Bq6GSJCCOifg',
    appId: '1:423502301630:ios:fd664563f1e68d778a11ef',
    messagingSenderId: '423502301630',
    projectId: 'comtwittercloneapp',
    storageBucket: 'comtwittercloneapp.firebasestorage.app',
    iosBundleId: 'com.example.twitterCloneApp',
  );
}
